services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mytheresa_app
    container_name: mytheresa_app
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: mytheresa
      MESSENGER_TRANSPORT_DSN: 'doctrine://default'
    depends_on:
      - db
    networks:
      - mytheresa_network

  nginx:
    image: nginx:latest
    container_name: mytheresa_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mytheresa_network

  db:
    image: mysql:8.0
    container_name: mytheresa_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mytheresa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mytheresa_network

volumes:
  db_data:

networks:
  mytheresa_network:
    driver: bridge